version: "3"
services:
  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    restart: always
    container_name: kmonad-spring-mongodb
    volumes:
      - "./db.init:/docker-entrypoint-initdb.d"
  service:
    build:
      context: ./kmonad-spring-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    container_name: kmonad-spring-service
    environment:
      - "SPRING_DATA_MONGODB_HOST=mongodb"
      - "SPRING_DATA_MONGODB_PORT=27017"
